// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_1MhLHxM_2MYWDShKF3zJqASuSMpJ0Q',
    appId: '1:63218994003:web:61a45d3f16986911896fa6',
    messagingSenderId: '63218994003',
    projectId: 'flutter-todo-app-14b85',
    authDomain: 'flutter-todo-app-14b85.firebaseapp.com',
    databaseURL: 'https://flutter-todo-app-14b85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-todo-app-14b85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm0CG3U2SHvi3V5GWSaQbfQR9SO-9s7J8',
    appId: '1:63218994003:ios:74cac38727d32ea3896fa6',
    messagingSenderId: '63218994003',
    projectId: 'flutter-todo-app-14b85',
    databaseURL: 'https://flutter-todo-app-14b85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-todo-app-14b85.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm0CG3U2SHvi3V5GWSaQbfQR9SO-9s7J8',
    appId: '1:63218994003:ios:3e5191c98ec286ee896fa6',
    messagingSenderId: '63218994003',
    projectId: 'flutter-todo-app-14b85',
    databaseURL: 'https://flutter-todo-app-14b85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-todo-app-14b85.appspot.com',
    iosBundleId: 'com.example.flutterTodoApp.RunnerTests',
  );
}
